<%
  uri = URI(ENV['MYSQL_URL'] || 'mysql://root:sql@mysql:3306/samson')
  uri.scheme = 'mysql2'
%>

production:
  adapter: sqlite3
  database: /storage/db/database.sqlite3
  pool: 5
  timeout: 5000

staging:
  adapter: sqlite3
  database: /storage/db/database.sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: sqlite3
  database: /storage/db/database.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: /storage/db/database.sqlite3
  pool: 5
  timeout: 5000

