#######################################
# Environment Configuration
#  - feel free to edit -
# -> for most changes you only have to
#         docker-compose up -d
#    to apply them
#######################################

#######################################
# Samson settings
MYSQL_URL=mysql://root:sql@mysql:3306/samson

# Extra features:
# (see https://github.com/zendesk/samson/blob/master/docs/extra_features.md#environment-and-deploy-group-managing)
# DEPLOY_GROUP_FEATURE=1
# JIRA_BASE_URL=http://jira.example.com/browse/

#######################################
# MySQL settings
# -> if you change these settings
#    you have to remove the database:
#         docker-compose rm mysql
#    because it's stored database in
#    volume and provisioning is only
#    done once.
MYSQL_ROOT_PASSWORD=sql
MYSQL_USER=samson
MYSQL_PASSWORD=samson
MYSQL_DATABASE=samson


