---

- local_action:
    module: slack
    token: "{{ notification_slack_token }}"
    username: "Samson deployment"
    msg:   ":airplane_arriving: Finished deployment of {{ PROJECT_NAME }}/{{ STAGE }} (revision: {{ REVISION }}, duration: {{ DEPLOYMENT_DURATION }})"
    color: "good"
    channel: "{{ notification_slack_channel | default(omit) }}"
  when: notification_slack_token is defined and notification_slack_token != ""
