---
- name: Deployment reporting tasks
  hosts: all
  gather_facts: false
  vars_files:
    - "applications/default.yml"
    - "applications/{{ DEPLOYMENT_APPLICATION | default('default') }}.yml"
    - "projects/{{ DEPLOYMENT_PROJECT | default('default') }}.yml"
  roles:
    - { role: deployment-status-startup, when: DEPLOYMENT_RC == "" }
    - { role: deployment-status-failure, when: DEPLOYMENT_RC != "" and DEPLOYMENT_RC != 0 }
    - { role: deployment-status-success, when: DEPLOYMENT_RC == 0 }
