---
- name: Deployment
  hosts: all
  vars_files:
    - "applications/default.yml"
    - "applications/{{ DEPLOYMENT_APPLICATION | default('default') }}.yml"
    - "projects/{{ DEPLOYMENT_PROJECT | default('default') }}.yml"
  roles:
    - { role: carlosbuenosvinos.ansistrano-deploy }
