---

- local_action:
    module: slack
    token: "{{ notification_slack_token }}"
    username: "Samson deployment"
    msg:   ":airplane_departure: Started deployment of {{ PROJECT_NAME }}/{{ STAGE }} (revision: {{ REVISION }}) by {{ DEPLOYER_NAME }}: {{ DEPLOY_URL }}"
    color: "normal"
    channel: "{{ notification_slack_channel | default(omit) }}"
  when: notification_slack_token is defined and notification_slack_token != ""
